# Configure your system!
MY_TIMEZONE='Mountain'
MY_HOSTNAME='starch'
MY_USERNAME='jny'
## Generated by running `openssl passwd -6`
MY_PASSWORD_ENC='$6$b86ol1GI01lkU3w.$DZBFk4cNa2HApGPG9u0QrIiYl4YHoXPLdMco0on4pyGnSvAxL1XBDhZaal7O88iSySUjY22cgYSmEfsSt97kN.'
ROOT_PASSWORD_ENV='$6$ntb/EyrhXbDlRZfH$MiiPso7wRW07dPlF/.r5k6bHjpgognXINFBpiKHgH.tMt06kRMxr/R/UDDD/C.SAVxLbqK.ehtd2C4wYI6CNO0'
MY_ROUTER_IP='192.168.0.1'

ROOT_FS='/mnt'

# Options are systemd-boot or grub 
BOOTLOADER='systemd-boot'
